### ISSUE TITLE
NotFound: No such file or directory

### ISSUE THREAD

**Issue by mikelue** [skanehira/denops-docker.vim#151]
Not working comands(I only tried these ones):
- `:DockerImages`
- `:e docker://images`

Error messages
```
[denops] NotFound: No such file or directory (os error 2)
[denops]     at Object.connect (ext:deno_net/01_net.js:486:66)
[denops]     at connect (file:///home/mike/.vim/plugged/denops-docker.vim/denops/docker/socket.ts:10:18)
[denops]     at request (file:///home/mike/.vim/plugged/denops-docker.vim/denops/docker/http.ts:35:24)
[denops]     at Module.get (file:///home/mike/.vim/plugged/denops-docker.vim/denops/docker/http.ts:77:22)
[denops]     at Module.images (file:///home/mike/.vim/plugged/denops-docker.vim/denops/docker/docker.ts:14:27)
[denops]     at Module.updateImagesBuffer (file:///home/mike/.vim/plugged/denops-docker.vim/denops/docker/action.ts:197:31)
[denops]     at eventLoopTick (ext:core/01_core.js:183:11)
[denops]     at async Object.images (file:///home/mike/.vim/plugged/denops-docker.vim/denops/docker/main.ts#46.541357:240:7)
[denops]     at async dispatch (https://deno.land/x/messagepack_rpc@v1.0.0/dispatcher.ts:36:12)
[denops]     at async Session.#dispatch (https://deno.land/x/messagepack_rpc@v1.0.0/session.ts:233:22)
```

My environment:

- VIM `9.0.1600`
- Deno
```
deno 1.35.3 (release, x86_64-unknown-linux-gnu)
v8 11.6.189.12
typescript 5.1.6
```
- denops.vim `v5.0.0`

Any response would be appreciated.

**Comment by skanehira** [comment]
@mikelue Thank you.
Maybe your environment doesn't exist `/var/run/docker.sock`
Can you run `docker context ls` and tell me that's output?

This is my output.
```sh
$ docker context ls                                               
NAME                TYPE                DESCRIPTION                               DOCKER ENDPOINT                                     KUBERNETES ENDPOINT   ORCHESTRATOR
default             moby                Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                                               
```

If your using Docker Desktop(on macOS), please check `Allow the default Docker socket to be used (requires password)` and restart, then you can run command.

<img width="1232" alt="image" src="https://github.com/skanehira/denops-docker.vim/assets/7888591/94a1751c-f181-4908-b381-86c1ca9076b4">

**Comment by mikelue** [comment]
```
NAME             DESCRIPTION                               DOCKER ENDPOINT               ERROR
default          Current DOCKER_HOST based configuration   unix:///var/run/docker.sock
dev-linux                                                  ssh://dev-linux
dev-minikube *                                             ssh://dev-minikube
pc-linux                                                   ssh://pc-linux
```

It seems that I'm using ssh tunnel to manage remote docker engine causing the problem.

**Comment by skanehira** [comment]
Seems like you have `unix:///var/run/docker.sock`
Can you check that file exists ?

```sh
ls unix:///var/run/docker.sock
```

**Comment by mikelue** [comment]
No, I don't have the file in my environment.(_Windows_, _WSL 2_, _Ubuntu 22.04_).

And I do use SSH for managing remote docker.

**Comment by skanehira** [comment]
Ok, I got the situation.
Sorry about this plugin doesn't support remote docker
Mabye implement it future if I have motivation

**Comment by skanehira** [comment]
If there is a away to bind remote docker socket communication to local socket, it may be works 🤔

**Comment by mikelue** [comment]
> If there is a away to bind remote docker socket communication to local socket, it might works 🤔

This is a viable solution.

Supporting context of docker may be a feature for this plugin.
